"""Only the original PDE II practice problems, fully worked in both modes."""

def populate(add,C,M,table):
    add(18,'Problem 1 · 구리 막대가 50도로 식는 시간',[
      C('주어진 값과 구할 것', M(r'\begin{gathered}L=80\ \mathrm{cm},\quad f(x)=100\sin\frac{\pi x}{80}\ {^\circ\mathrm C},\quad u(0,t)=u(80,t)=0,\\\rho=8.92\ \mathrm{g/cm^3},\quad c_p=0.092\ \mathrm{cal/(g\,{^\circ C})},\quad \kappa=0.95\ \mathrm{cal/(cm\,s\,{^\circ C})}.\end{gathered}'), 'Laterally insulated(옆면이 단열된) 구리 막대의 u(x,t)와 maximum temperature(최대온도)가 50도가 되는 시간을 구합니다. 원본의 κ는 thermal conductivity(열전도율)이며 열확산계수 자체가 아닙니다. 원본 2쪽의 K,C를 여기서는 κ,cₚ로 표기했습니다.'),
      C('1 · 열확산계수와 단위를 계산합니다.', M(r'\alpha=c^2=\frac{\kappa}{\rho c_p}=\frac{0.95}{8.92(0.092)}=1.1576330669\ \mathrm{cm^2/s}'), M(r'\frac{\mathrm{cal/(cm\,s\,{^\circ C})}}{[\mathrm{g/cm^3}][\mathrm{cal/(g\,{^\circ C})}]}=\mathrm{cm^2/s}'), '모든 자료가 cm,g,s,cal 단위계로 맞아 있으므로 80을 m로 바꿀 필요가 없습니다. 변환한다면 전체를 일관되게 바꿔야 합니다.'),
      C('2 · 초기온도는 첫 사인 모드 하나입니다.', M(r'B_n=\frac2{80}\int_0^{80}100\sin\frac{\pi x}{80}\sin\frac{n\pi x}{80}\,dx=\begin{cases}100,&n=1,\\0,&n\ne1.\end{cases}'), M(r'\boxed{u(x,t)=100\sin\frac{\pi x}{80}\,\exp\!\left[-\frac{0.95}{8.92(0.092)}\left(\frac{\pi}{80}\right)^2t\right]}'), M(r'u(x,t)\simeq100\sin\frac{\pi x}{80}\,e^{-0.0017852156893t}\quad[{^\circ C}],\qquad t\ [\mathrm s]')),
      C('3 · 최대 위치와 최대온도를 구합니다.', '0≤x≤80에서 sin(πx/80)의 최댓값은 1이며 x=40에서 달성됩니다. 시간 배율은 양수이고 x에 의존하지 않으므로 최대 위치는 변하지 않습니다.', M(r'u_{\max}(t)=u(40,t)=100e^{-rt},\qquad r=\alpha(\pi/80)^2')),
      C('4 · 로그를 취해 시간을 풉니다.', M(r'100e^{-rt}=50\Rightarrow e^{-rt}=\frac12\Rightarrow -rt=\ln\frac12=-\ln2'), M(r'\boxed{t_{50}=\frac{80^2\ln2}{\alpha\pi^2}=\frac{80^2(8.92)(0.092)\ln2}{0.95\pi^2}=388.2708\ \mathrm s\simeq6.4712\ \mathrm{min}}'), '약 6분 28.3초입니다. 지수 안의 t는 초 단위이므로 분 변환은 마지막에 합니다. 이는 특정 모드의 절반 감쇠 시간이며 임의의 초기온도에 항상 같은 단일 지수 최대온도 공식을 적용하는 것은 아닙니다.'),
      C('5 · 원식·조건·요구 온도로 검산합니다.', M(r'u_t=-r u,\quad u_{xx}=-(\pi/80)^2u,\quad u_t=\alpha u_{xx};\qquad u(40,t_{50})=50'), 't=0에서 f(x), 양 끝에서 0도가 맞습니다. 단열은 옆면 조건이므로 막대 끝을 통한 냉각과 모순되지 않습니다.')
    ],[
      C('1 · 문제의 문장을 계산 항목으로 바꿉니다.', '80 cm 길이의 막대 옆면에는 열이 새지 않지만 양 끝은 0도로 냉각됩니다. 처음 온도 100sin(πx/80)은 왼쪽 0도, 가운데 100도, 오른쪽 0도인 반쪽 사인 모양입니다. 구할 것은 모든 위치의 이후 온도와 가장 뜨거운 곳이 50도까지 내려가는 시간입니다.', M(r'L=80,\quad f(x)=100\sin\frac{\pi x}{80},\quad u(0,t)=u(80,t)=0')),
      C('2 · 0.95를 지수에 바로 넣지 않습니다.', '0.95는 thermal conductivity(열전도율) κ입니다. PDE가 요구하는 thermal diffusivity(열확산계수) c²는 이것을 밀도와 비열의 곱으로 나눈 값입니다.', M(r'\rho c_p=8.92\times0.092=0.82064'), M(r'c^2=\alpha=\frac{0.95}{0.82064}=1.1576330669\ \mathrm{cm^2/s}'), '지수에는 이 숫자를 한 번 곱합니다. 이미 c²이므로 또 제곱하지 않습니다. 길이를 80 cm로 사용하므로 cm²/s라는 단위도 잘 맞습니다.'),
      C('3 · 많은 계수를 구할 필요가 없는 이유', '일반해의 공간 부품은 sin(nπx/L)입니다. L=80,n=1이면 문제의 sin(πx/80)과 완전히 같습니다. 그러므로 첫 부품을 100개만 쓰고 나머지는 0개 쓰면 됩니다. Fourier coefficient(푸리에 계수)로 쓰면 B₁=100이고 n≥2에서는 Bₙ=0입니다.', M(r'u(x,t)=100\sin\frac{\pi x}{80}e^{-\alpha(\pi/80)^2t}'), '원한다면 적분으로도 확인할 수 있습니다. 첫 모드의 제곱 적분은 L/2=40이므로 B₁=(2/80)×100×40=100입니다. 서로 다른 사인끼리는 orthogonality(직교성) 때문에 적분이 0입니다.'),
      C('4 · 최대온도는 x를 먼저 골라야 합니다.', '지수 배율은 모든 위치에 똑같이 곱합니다. 따라서 사인이 가장 큰 곳이 항상 가장 뜨겁습니다. sin θ는 θ=π/2에서 1이고, πx/80=π/2를 풀면 x=40입니다.', M(r'\frac{\pi x}{80}=\frac\pi2\Rightarrow x=40,\qquad u_{\max}(t)=100e^{-rt}'), M(r'r=1.1576330669\left(\frac\pi{80}\right)^2=0.0017852156893\ \mathrm{s^{-1}}'), 'Maximum(최대값)을 묻는데 막대의 아무 위치나 고르면 요구한 시간을 구할 수 없습니다.'),
      C('5 · 로그는 지수 속에 숨어 있는 t를 꺼내 줍니다.', M(r'100e^{-rt}=50\quad\Rightarrow\quad e^{-rt}=0.5'), '양변의 natural logarithm(자연로그) ln을 취하면 ln(eᵃ)=a이므로 왼쪽은 −rt가 됩니다. 오른쪽 ln(0.5)은 음수이고 약 −0.693147입니다.', M(r'-rt=\ln0.5=-0.693147\ldots\quad\Rightarrow\quad t=\frac{0.693147\ldots}{0.0017852156893}'), M(r'\boxed{t\simeq388.27\ \mathrm s=6.47\ \mathrm{min}\simeq6\text{분}\ 28.3\text{초}}'), '시간이 양수로 나오는지 확인합니다. 처음부터 분을 대입하면 단위가 어긋납니다. 초로 답을 얻은 뒤 60으로 나누십시오.'),
      C('6 · 마지막 검산', 't=0을 넣으면 e⁰=1이라 처음 온도가 돌아옵니다. x=0이나 80에서는 사인이 0이라 양 끝 조건을 만족합니다. x=40,t=388.27초에서는 e⁻ʳᵗ≈0.5라 50도가 됩니다. 일반식과 숫자 답을 모두 썼으므로 두 가지 요구에 답했습니다.', M(r'\boxed{u(x,t)\simeq100\sin\frac{\pi x}{80}\,e^{-0.0017852156893t}\quad(t\text{ in seconds})}'))
    ],role='원본 연습문제·완성 풀이')

    add(21,'Problem 2 · 삼각형 초기온도의 계수를 끝까지 계산합니다.',[
      C('문제의 높이와 구간을 그대로 보존합니다.', M(r'T_t=c^2T_{xx},\quad T(0,t)=T(L,t)=0,\qquad f(x)=\begin{cases}x,&0\le x\le L/2,\\L-x,&L/2\le x\le L.\end{cases}'), '중앙 높이는 L/2입니다. PDE I의 높이 k인 삼각형과 모양은 같지만 계수 배율은 다릅니다. 원본 그림은 L=π인 경우이고 다음 페이지의 시간 그림은 c=1까지 지정합니다. 아래에서는 먼저 일반 L,c의 식을 구합니다.'),
      C('1 · 꺾이는 점에서 계수 적분을 나눕니다.', M(r'B_n=\frac2L\left[\int_0^{L/2}x\sin(k_nx)\,dx+\int_{L/2}^L(L-x)\sin(k_nx)\,dx\right],\qquad k_n=\frac{n\pi}{L}')),
      C('2 · 두 부분적분을 각각 계산합니다.', M(r'\int x\sin(kx)dx=-\frac{x\cos(kx)}k+\frac{\sin(kx)}{k^2}'), M(r'I_1=-\frac{L}{2k_n}\cos\frac{n\pi}{2}+\frac1{k_n^2}\sin\frac{n\pi}{2}'), M(r'\int(L-x)\sin(kx)dx=-\frac{(L-x)\cos(kx)}k-\frac{\sin(kx)}{k^2}'), M(r'I_2=\frac{L}{2k_n}\cos\frac{n\pi}{2}+\frac1{k_n^2}\sin\frac{n\pi}{2}'), '두 번째 적분에서 d(L−x)/dx=−1이므로 사인 항의 부호가 첫 번째와 다릅니다. 상한 L에서 (L−L)=0,sin nπ=0이 되어 경계항이 모두 사라집니다.'),
      C('3 · 합하면 코사인 경계항이 상쇄됩니다.', M(r'B_n=\frac2L(I_1+I_2)=\frac4{Lk_n^2}\sin\frac{n\pi}{2}=\boxed{\frac{4L}{n^2\pi^2}\sin\frac{n\pi}{2}}'), M(r'B_{2m}=0,\qquad B_{2m+1}=\frac{4L(-1)^m}{(2m+1)^2\pi^2},\quad m=0,1,2,\ldots'), 'sin(nπ/2)의 값은 1,0,−1,0,…입니다. 중앙 대칭인 초기온도와 중앙에 대해 반대칭인 짝수 모드의 곱이 상쇄된다는 해석과도 일치합니다.'),
      C('4 · 각 모드에 시간 감쇠를 붙입니다.', M(r'\boxed{T(x,t)=\frac{4L}{\pi^2}\sum_{m=0}^{\infty}\frac{(-1)^m}{(2m+1)^2}\sin\frac{(2m+1)\pi x}{L}\,e^{-c^2((2m+1)\pi/L)^2t}}'), M(r'L=\pi,\ c=1:\quad\boxed{T(x,t)=\frac4\pi\sum_{m=0}^{\infty}\frac{(-1)^m}{(2m+1)^2}\sin[(2m+1)x]e^{-(2m+1)^2t}}'), M(r'T(x,t)=\frac4\pi\left(e^{-t}\sin x-\frac{e^{-9t}}9\sin3x+\frac{e^{-25t}}{25}\sin5x-\cdots\right)'), '각 사인마다 자기 n²에 해당하는 지수가 붙습니다. 전체 급수에 e⁻ᵗ 하나만 곱하면 초기 모양 전체가 같은 속도로 줄어드는 잘못된 해가 됩니다.'),
      C('5 · 초기·경계조건과 PDE의 검산', '각 항은 양 끝에서 0이고 Tₜ=c²Tₓₓ를 만족합니다. t=0에서 삼각형의 사인 급수가 되며 이 연속인 조각별 선형 함수에 수렴합니다. 초기 꼭짓점은 두 번 미분 가능하지 않지만 t>0에는 지수 감쇠로 매끄러워집니다. 꼭짓점의 t=0에 고전적인 두 번 미분을 억지로 요구하지 않습니다.')
    ],[
      C('1 · 이 삼각형의 꼭대기는 1이 아닙니다.', 'Initial temperature(초기온도)는 왼쪽 절반에서 x, 오른쪽 절반에서 L−x입니다. 중앙 x=L/2에 넣으면 두 식 모두 L/2입니다. 따라서 높이를 1이나 이전 파동 문제의 k로 착각하면 모든 coefficient(계수)가 틀어집니다.', M(r'f(x)=\begin{cases}x,&0\le x\le L/2,\\L-x,&L/2\le x\le L,\end{cases}\qquad f(L/2)=L/2')),
      C('2 · 공식에 넣되 함수가 달라지는 곳에서 나눕니다.', '양 끝이 0이므로 Fourier sine series(푸리에 사인 급수)를 씁니다. n번째 계수 공식의 적분 안에 f(x)를 넣어야 하는데, 절반을 지나면 식이 바뀝니다. 그래서 같은 점 L/2에서 적분도 둘로 나눕니다.', M(r'B_n=\frac2L\left[\int_0^{L/2}x\sin\frac{n\pi x}{L}dx+\int_{L/2}^L(L-x)\sin\frac{n\pi x}{L}dx\right]'), '길게 반복되는 nπ/L를 k라고 잠시 쓰겠습니다. 이 적분에서 n,L,k는 상수이고 x만 변수입니다.'),
      C('3 · 왼쪽 절반: x를 미분하고 사인을 적분합니다.', M(r'\int p\,dq=pq-\int q\,dp,\qquad p=x,\ dp=dx,\ dq=\sin(kx)dx,\ q=-\frac{\cos(kx)}k'), 'cos(kx)를 미분하면 −k sin(kx)이므로, sin(kx)를 적분할 때 −cos(kx)/k가 됩니다. 그다음 cos(kx)를 적분하면 sin(kx)/k여서 k가 한 번 더 분모에 생깁니다.', M(r'\int x\sin(kx)dx=-\frac{x\cos(kx)}k+\frac1k\int\cos(kx)dx=-\frac{x\cos(kx)}k+\frac{\sin(kx)}{k^2}'), M(r'I_1=\left[-\frac{x\cos(kx)}k+\frac{\sin(kx)}{k^2}\right]_0^{L/2}=-\frac{L\cos(n\pi/2)}{2k}+\frac{\sin(n\pi/2)}{k^2}'), 'kL/2=nπ/2를 썼습니다. 아래끝 x=0에서는 x=0과 sin 0=0 때문에 두 항 모두 0입니다.'),
      C('4 · 오른쪽 절반: L−x의 미분은 −1입니다.', M(r'p=L-x,\quad dp=-dx,\quad dq=\sin(kx)dx,\quad q=-\frac{\cos(kx)}k'), M(r'\int(L-x)\sin(kx)dx=-\frac{(L-x)\cos(kx)}k-\frac1k\int\cos(kx)dx=-\frac{(L-x)\cos(kx)}k-\frac{\sin(kx)}{k^2}'), '부분적분의 바깥 마이너스와 q,dp의 부호를 하나씩 확인합니다. 왼쪽 적분과 마지막 사인 항의 부호가 다릅니다. 이제 위끝 값을 넣고 아래끝 값을 뺍니다.', M(r'I_2=0-\left[-\frac{L\cos(n\pi/2)}{2k}-\frac{\sin(n\pi/2)}{k^2}\right]=\frac{L\cos(n\pi/2)}{2k}+\frac{\sin(n\pi/2)}{k^2}'), '위끝 x=L에서는 L−x=0이고 sin(kL)=sin(nπ)=0입니다. 대괄호 전체를 빼기 때문에 아래끝의 두 마이너스가 모두 플러스로 바뀝니다.'),
      C('5 · 둘을 더하고 2/L까지 곱합니다.', M(r'I_1+I_2=\frac2{k^2}\sin\frac{n\pi}{2},\qquad B_n=\frac2L\frac2{k^2}\sin\frac{n\pi}{2}'), M(r'\frac1{k^2}=\frac{L^2}{n^2\pi^2}\quad\Rightarrow\quad\boxed{B_n=\frac{4L}{n^2\pi^2}\sin\frac{n\pi}{2}}'), 'n=1,2,3,4,5,…에서 sin(nπ/2)=1,0,−1,0,1,…입니다. 짝수 n은 사라지고 홀수 n만 부호를 번갈아 갖습니다.', M(r'B_1=\frac{4L}{\pi^2},\quad B_2=0,\quad B_3=-\frac{4L}{9\pi^2},\quad B_4=0,\quad B_5=\frac{4L}{25\pi^2}')),
      C('6 · 답은 계수에서 끝나지 않습니다.', '각 Bₙ에 공간 사인과 시간 감쇠를 곱해 모두 더해야 temperature(온도) T(x,t)가 됩니다. 같은 계수라도 파동 문제처럼 cos(λₙt)를 붙이지 않습니다.', M(r'\boxed{T(x,t)=\sum_{n=1}^{\infty}\frac{4L}{n^2\pi^2}\sin\frac{n\pi}{2}\sin\frac{n\pi x}{L}e^{-c^2(n\pi/L)^2t}}'), '원본 그림의 L=π와 다음 슬라이드의 c=1을 넣으면 nπ/L=n입니다. 짝수항은 0이므로 다음처럼 간단해집니다.', M(r'\boxed{T(x,t)=\frac4\pi\left(e^{-t}\sin x-\frac{e^{-9t}}9\sin3x+\frac{e^{-25t}}{25}\sin5x-\cdots\right)}'), 't=0에는 모든 감쇠 인자가 1이라 삼각형으로 돌아갑니다. x=0,π에서는 모든 사인이 0입니다. 시간이 지나면 9t,25t가 붙은 항들이 빨리 줄어 첫 번째 둥근 모양이 남습니다.')
    ],role='원본 연습문제·완성 풀이')

    add(22,'삼각형 온도는 왜 둥글어지며 내려갈까요?',[
      C('원본 그림의 L=π,c=1을 적용합니다.', M(r'T(x,t)=\frac4\pi\sum_{m\ge0}\frac{(-1)^m}{(2m+1)^2}\sin[(2m+1)x]e^{-(2m+1)^2t}'), '그림은 t=0,0.1,0.5,2의 변화입니다. 높은 mode(모드)가 더 빠르게 감쇠하여 초기 꼭짓점이 즉시 매끄러워집니다. 충분히 큰 t에는 B₁이 0이 아니므로 T≈(4/π)e⁻ᵗsin x입니다.'),
      C('중심값은 교대부호가 다시 사라집니다.', M(r'\sin[(2m+1)\pi/2]=(-1)^m\quad\Rightarrow\quad T(\pi/2,t)=\frac4\pi\sum_{m\ge0}\frac{e^{-(2m+1)^2t}}{(2m+1)^2}'), 'B₂ₘ₊₁의 (−1)ᵐ와 중심에서의 사인 (−1)ᵐ가 곱해져 양수가 됩니다. 시간에 따라 각 양의 항이 감소합니다. t=0에서 ∑ₘ₌₀∞1/(2m+1)²=π²/8이므로 T(π/2,0)=π/2로 원본 삼각형의 높이와 맞습니다.'),
      C('무한 막대와 달리 끝을 통해 열을 잃습니다.', M(r'\frac{d}{dt}\int_0^LT(x,t)\,dx=c^2[T_x(L,t)-T_x(0,t)]'), 'Temperature fixed at zero(온도 0으로 고정)인 끝에서는 열이 빠질 수 있습니다. 전체 온도 적분이 일정해야 한다고 검산하면 이 유한 막대 문제를 잘못 판단하게 됩니다. 아래 조작 그림은 원본 문제의 급수만 계산합니다.')
    ],[
      C('1 · 처음 삼각형은 작은 물결들의 합입니다.', '삼각형 꼭짓점을 만들려면 첫 사인 하나만으로는 부족해서 sin 3x,sin 5x,…를 보탭니다. Heat equation(열방정식)에서는 3번째 성분에 e⁻⁹ᵗ, 5번째에 e⁻²⁵ᵗ가 붙어 첫 번째의 e⁻ᵗ보다 빨리 줄어듭니다. 그래서 뾰족한 부분이 빨리 둥글어집니다.', M(r'T(x,t)\approx\frac4\pi e^{-t}\sin x\qquad\text{큰 }t\text{에서}'), '이 식은 원래 급수의 장시간 근사입니다. t=0의 삼각형을 이 한 항으로 정확하게 대체할 수는 없습니다.'),
      C('2 · 중심에서는 왜 전부 더하기가 되나요?', 'n=3의 coefficient(계수)는 음수이지만 중심에서 sin(3π/2)도 −1입니다. 둘을 곱하면 양수입니다. n=5에서는 둘 다 +1이고, 이런 패턴이 반복됩니다.', M(r'T(\pi/2,t)=\frac4\pi\left(e^{-t}+\frac{e^{-9t}}9+\frac{e^{-25t}}{25}+\cdots\right)'), '따라서 중심의 온도는 각 양의 감쇠항을 더한 값입니다. t=0일 때는 π/2라는 원래 높이에 맞고, 시간이 지나면 0에 가까워집니다.'),
      C('3 · 앞의 무한 막대와 총열 검사가 다릅니다.', 'Infinite bar(무한 막대)는 양 끝이 없어서 온도가 넓게 퍼져도 전체 열이 보존됐습니다. 이번에는 양 끝을 0도로 유지하므로 열을 밖으로 빼냅니다. Laterally insulated(옆면이 단열된)라는 조건만으로 “모든 경계에서 열이 못 나간다”고 해석하면 안 됩니다.', '아래 시간 조절로 원본 문제의 처음 삼각형과 이후 곡선을 비교하십시오. t=0에서는 처음 삼각형을 정확하게 그리고, t>0에서는 수렴이 빠른 Fourier series(푸리에 급수)를 계산합니다.')
    ],role='원본 결과 그림·검산')
