"""Separation of variables: full derivation with a separate beginner route."""
def populate(add, C, M, table):
    add(5, '고정된 줄의 파동방정식 · 변수분리의 전체 유도', [
      C('PDE, 경계조건, 초기조건의 역할', M(r"\begin{gathered}u_{tt}=c^2u_{xx},\quad 0<x<L,\quad t>0,\quad c>0,\\u(0,t)=u(L,t)=0,\\u(x,0)=f(x),\qquad u_t(x,0)=g(x).\end{gathered}"), 'u는 줄의 횡변위, L은 길이, c는 wave speed(파동 속도)입니다. Boundary conditions(경계조건)는 모든 시간에 양 끝을 고정하고, initial conditions(초기조건)는 처음의 모양 f와 속도 g를 지정합니다. 연속적인 해에는 f(0)=f(L)=0이 필요하며, 끝점까지 시간 미분이 연속이면 g(0)=g(L)=0도 필요합니다. 더 매끄러운 고전해에는 추가 적합조건이 따릅니다.'),
      C('편집자 보강 · 왜 곡률과 가속도가 연결되는가?', '장력 T와 선밀도 ρ가 일정하고, 기울기가 작으며 감쇠·외력이 없는 가는 줄을 생각합니다. 짧은 구간 Δx의 양 끝 장력이 주는 수직 힘의 차는 T[uₓ(x+Δx)−uₓ(x)]입니다. 질량 ρΔx에 Newton’s second law(뉴턴 제2법칙)를 적용하고 Δx→0으로 보냅니다.', M(r"\rho\Delta x\,u_{tt}\approx T[u_x(x+\Delta x,t)-u_x(x,t)]\quad\Rightarrow\quad u_{tt}=\frac{T}{\rho}u_{xx},\quad c=\sqrt{T/\rho}"), '원본은 이 물리 유도를 적지 않았습니다. 여기의 가정은 모델을 이해하기 위한 보강이며, c의 단위는 길이/시간입니다.'),
      C('1 · 곱의 형태를 시도하고 상수로 분리합니다.', 'Separation of variables(변수분리법)는 먼저 u=F(x)G(t)인 비영 해를 찾는 방법입니다. 모든 해가 단 하나의 곱으로 표현된다고 가정하는 것은 아닙니다.', M(r"FG''=c^2F''G\quad\Rightarrow\quad\frac{F''}{F}=\frac{G''}{c^2G}=-\mu"), '왼쪽은 x만, 오른쪽은 t만의 함수이므로 서로 독립인 모든 x,t에서 같으려면 공통 상수여야 합니다. F,G가 0이 아닌 곳에서 나눈 뒤 얻는 미분방정식은 원래의 곱 해 전체에 적용합니다. −μ의 음수는 표기 선택이며 μ&gt;0은 다음 단계에서 증명합니다.', M(r"F''+\mu F=0,\quad F(0)=F(L)=0;\qquad G''+c^2\mu G=0")),
      C('2 · μ≤0에서는 비영 공간해가 없습니다.', M(r"\begin{aligned}\mu=0:&\quad F=a+bx,\ F(0)=0\Rightarrow a=0,\ F(L)=0\Rightarrow b=0.\\\mu=-\alpha^2<0:&\quad F=a\cosh(\alpha x)+b\sinh(\alpha x),\\&\quad F(0)=0\Rightarrow a=0,\quad b\sinh(\alpha L)=0\Rightarrow b=0.\end{aligned}"), 'α,L&gt;0이면 sinh(αL)≠0입니다. 두 경우 모두 u=0만 주므로 비영 정상모드를 만드는 데는 쓰이지 않습니다.'),
      C('3 · μ&gt;0일 때 양 끝의 조건이 허용 파장을 고릅니다.', M(r"\begin{aligned}\mu=\kappa^2>0:&\quad F=a\cos(\kappa x)+b\sin(\kappa x),\\F(0)=0&\Rightarrow a=0,\\F(L)=0&\Rightarrow b\sin(\kappa L)=0,\\b\ne0&\Rightarrow \kappa L=n\pi\quad(n=1,2,\ldots).\end{aligned}"), 'n=0은 이미 제외한 영해이고 음의 n은 같은 사인함수에 부호만 바꿉니다. 따라서 공간 eigenvalue(고유값)와 eigenfunction(고유함수)는 다음과 같습니다.', M(r"\mu_n=\left(\frac{n\pi}{L}\right)^2,\qquad F_n(x)=\sin\frac{n\pi x}{L}")),
      C('4 · 시간 방정식과 결합해 한 모드를 완성합니다.', M(r"\lambda_n=c\sqrt{\mu_n}=\frac{cn\pi}{L},\qquad G_n''+\lambda_n^2G_n=0"), M(r"\boxed{u_n(x,t)=\left(B_n\cos\lambda_nt+B_n^*\sin\lambda_nt\right)\sin\frac{n\pi x}{L}}"), '공간해의 상수배는 Bₙ,Bₙ*에 흡수했습니다. 이 단계에서는 PDE와 경계조건만 맞췄습니다. 임의의 f,g를 맞추려면 여러 모드를 더하고 10쪽의 Fourier coefficients(푸리에 계수)를 결정해야 합니다.')
    ], [
      C('1 · 찾아야 하는 것은 움직이는 줄 전체의 높이입니다.', 'x는 줄 위의 위치, t는 시간, u(x,t)는 그 위치의 높이입니다. u(0,t)=u(L,t)=0은 양 끝이 계속 못에 고정되어 있다는 뜻입니다. f(x)는 손을 놓는 순간의 모양, g(x)는 그 순간 각 점이 움직이는 속도입니다. 같은 모양에서도 위로 밀며 놓는지 가만히 놓는지에 따라 이후 움직임이 달라져 두 initial conditions(초기조건)가 필요합니다.', M(r"u(x,0)=f(x),\qquad u_t(x,0)=g(x),\qquad u_{tt}=c^2u_{xx}"), 'f와 g는 높이와 속도라는 서로 다른 정보를 담습니다. 양 끝을 고정하므로 처음의 높이도 f(0)=f(L)=0이어야 합니다. 끝점 속도까지 연속적으로 정의하면 그 속도 역시 0이어야 합니다.'),
      C('2 · 먼저 쉬운 모양 하나만 찾아봅니다.', '시간이 지나도 모양의 비율은 같고 높이만 커졌다 작아지는 진동을 상상해 보십시오. 공간 모양 F(x)에 시간별 배율 G(t)를 곱하면 그런 움직임이 됩니다. 이 시도가 separation of variables(변수분리법)입니다. 처음부터 어떤 줄 모양이든 곱 하나로 된다고 우기는 것이 아니라, 나중에 섞어 쓸 기본 재료를 찾는 것입니다.', M(r"u(x,t)=F(x)G(t),\quad u_{xx}=F''(x)G(t),\quad u_{tt}=F(x)G''(t)"), 'x로 미분할 때 G(t)는 상수처럼 남고, t로 미분할 때 F(x)가 남습니다. 편미분이 익숙해지면 이 대입까지는 보통의 미분 계산입니다.'),
      C('3 · 왜 갑자기 −μ라는 숫자를 놓나요?', M(r"FG''=c^2F''G\quad\Rightarrow\quad \frac{F''(x)}{F(x)}=\frac{G''(t)}{c^2G(t)}"), '시간 t를 하나 고정해 보십시오. 오른쪽은 이제 숫자 하나입니다. 왼쪽은 x를 바꿔도 그 숫자와 같아야 하므로 상수입니다. 반대로 x를 고정해도 같은 결론입니다. 그 공통 숫자에 −μ라는 이름을 붙입니다. 음수를 쓴 것은 나중에 사인 방정식으로 쓰기 편한 표기이고, μ가 양수라는 결론은 아직 내리지 않았습니다.', M(r"F''=-\mu F,\qquad G''=-c^2\mu G"), '0으로 나눌 수 없으므로 F,G가 0이 아닌 구간에서 위 나눗셈을 합니다. 얻은 사인·코사인 해는 0이 되는 점에서도 원래 미분방정식에 대입해 확인할 수 있습니다.'),
      C('4 · 양 끝이 0인 직선이나 지수곡선은 왜 탈락할까요?', '움직임이 아예 없는 G≡0을 제외하면 F(0)=F(L)=0이어야 합니다. μ=0이면 F″=0이므로 F=a+bx라는 직선입니다. 양 끝이 0인 직선은 그냥 0입니다. μ&lt;0이면 α&gt;0을 써서 μ=−α²로 두고 지수함수로 풉니다.', M(r"\begin{aligned}F&=a e^{\alpha x}+b e^{-\alpha x},\\F(0)=0&\Rightarrow b=-a,\\F(L)=0&\Rightarrow a(e^{\alpha L}-e^{-\alpha L})=0\Rightarrow a=b=0.\end{aligned}"), 'eᵅᴸ와 e⁻ᵅᴸ는 같지 않으므로 마지막 식에서 a=0입니다. 결국 μ≤0에서는 줄이 진동하는 재료를 얻지 못합니다.'),
      C('5 · 사인파는 딱 맞는 길이에서 양 끝이 0입니다.', '남은 μ&gt;0을 κ²라고 쓰면 F″=−κ²F입니다. 사인과 코사인은 두 번 미분하면 음의 배수가 되므로 이 식을 만족합니다.', M(r"\begin{aligned}F&=a\cos(\kappa x)+b\sin(\kappa x),\\F(0)&=a=0,\\F(L)&=b\sin(\kappa L)=0.\end{aligned}"), 'b=0이면 또 아무 진동이 없으므로 sin(κL)=0이어야 합니다. 고등학교에서 배운 사인함수의 영점은 π,2π,3π,…이므로 κ=nπ/L입니다. 줄 안에 반 파장이 정수 개 들어가는 모양만 허용되는 것입니다.', M(r"F_n(x)=\sin\frac{n\pi x}{L},\quad \mu_n=\frac{n^2\pi^2}{L^2},\quad n=1,2,\ldots")),
      C('6 · 그 모양은 시간에 따라 어떻게 흔들리나요?', '공간 모양을 정하면 μₙ도 정해집니다. 시간식은 G″=−(cnπ/L)²G가 되어 또 사인·코사인으로 풀립니다. λₙ=cnπ/L이라는 이름을 쓰면 훨씬 짧아집니다.', M(r"G_n(t)=B_n\cos(\lambda_nt)+B_n^*\sin(\lambda_nt),\qquad \lambda_n=\frac{cn\pi}{L}"), M(r"u_n(x,t)=\left[B_n\cos(\lambda_nt)+B_n^*\sin(\lambda_nt)\right]\sin\frac{n\pi x}{L}"), 'Bₙ과 Bₙ*는 아직 정하지 않은 두 coefficient(계수)입니다. 공간 사인은 “어떤 모양인가”, 시간 괄호는 “얼마나 빠르게 어떤 위상으로 움직이나”를 말합니다. 10쪽에서 처음의 모양과 속도를 이용해 이 두 수를 구합니다.'),
      C('7 · 방정식이 실제 줄과 연결되는 이유 · 편집자 보강', '살짝 굽은 줄 조각의 양 끝에서는 장력이 약간 다른 방향으로 당깁니다. 그 수직 성분의 차이가 굽은 정도 uₓₓ에 비례하고, 힘=질량×가속도이므로 uₜₜ와 연결됩니다. 기울기가 작고 장력 T와 선밀도 ρ가 일정하며 감쇠·외력을 무시하면 c²=T/ρ입니다.', M(r"\rho\Delta x\,u_{tt}\approx T[u_x(x+\Delta x)-u_x(x)]\quad\Rightarrow\quad u_{tt}=\frac{T}{\rho}u_{xx}"), 'c는 높이가 올라가는 속도가 아니라 변형이 줄을 따라 전달되는 wave speed(파동 속도)입니다. 줄의 각 점의 위아래 속도는 uₜ입니다.')
    ])

    add(9, 'Normal modes(정상모드) · 모양과 진동수', [
      C('공간 모양과 시간 진동을 분리해서 읽습니다.', M(r"u_n=(B_n\cos\lambda_nt+B_n^*\sin\lambda_nt)\sin\frac{n\pi x}{L},\qquad \lambda_n=\frac{cn\pi}{L}"), 'Normal mode(정상모드)는 고정된 공간 형태로 진동하는 하나의 독립 진동입니다. n번째 모드는 내부에 n−1개의 node(마디)를 가지며, 그 위치는 x=jL/n, j=1,…,n−1입니다. 양 끝도 마디입니다.', M(r"\text{wavelength }\ell_n=\frac{2L}{n},\qquad \text{period }T_n=\frac{2L}{nc},\qquad \text{frequency }\nu_n=\frac{nc}{2L}")),
      C('원본의 eigenvalue(고유값) 표기 읽기', '원본은 λₙ=cnπ/L을 eigenvalue(고유값)라고 부릅니다. 이 λₙ는 시간 코사인의 angular frequency(각주파수)이며 단위는 rad/s입니다. 공간 연산자 −d²/dx²의 eigenvalue(고유값)는 μₙ=(nπ/L)²입니다. 둘은 λₙ²=c²μₙ로 연결됩니다. 기호를 서로 바꾸어 넣지 마십시오.', M(r"-F_n''=\mu_nF_n,\qquad G_n''+\lambda_n^2G_n=0,\qquad \lambda_n=2\pi\nu_n")),
      C('계수와 spectrum(스펙트럼)', '원본의 Bₙ*는 Bₙ과 독립인 사인항 계수 표기이며 이 실수해 문맥에서 complex conjugate(복소켤레)를 뜻하지 않습니다. 별표를 지수나 곱셈으로 읽지 않습니다. {λ₁,λ₂,…}는 허용되는 각주파수 목록인 spectrum(스펙트럼)입니다. n=2,3,…는 기본 진동수의 정수배입니다.')
    ], [
      C('1 · 원본의 네 그림은 네 가지 기본 재료입니다.', 'n=1은 가운데가 한 번 부푼 모양, n=2는 위아래로 두 반파가 들어간 모양입니다. 이것들이 normal mode(정상모드)입니다. 한 모드만 진동하면 사인 곡선 모양은 유지되고 전체 높이와 부호만 바뀝니다.', M(r"n=1:\ \sin\frac{\pi x}{L},\qquad n=2:\ \sin\frac{2\pi x}{L}"), 'Node(마디)는 시간이 흘러도 높이가 계속 0인 점입니다. n=2에서는 가운데 x=L/2가 마디이고, 일반적으로 내부 마디는 n−1개입니다.'),
      C('2 · 공간의 사인과 시간의 사인은 맡은 일이 다릅니다.', M(r"u_n=\underbrace{[B_n\cos(\lambda_nt)+B_n^*\sin(\lambda_nt)]}_{\text{시간에 따른 배율}}\underbrace{\sin(n\pi x/L)}_{\text{줄의 공간 모양}}"), 'λₙ가 클수록 시간 괄호가 더 빨리 반복됩니다. 코사인은 각도가 2π 증가할 때 한 바퀴이므로 λₙTₙ=2π입니다.', M(r"\lambda_n=\frac{cn\pi}{L},\qquad T_n=\frac{2\pi}{\lambda_n}=\frac{2L}{cn},\qquad \nu_n=\frac1{T_n}=\frac{cn}{2L}"), 'Frequency(진동수) νₙ는 초당 진동 횟수인 Hz, angular frequency(각주파수) λₙ는 초당 각도인 rad/s입니다. 2π배 차이입니다.'),
      C('3 · 같은 고유값이라는 이름 아래 두 수를 구별합니다.', '원본은 λₙ를 eigenvalue(고유값)라고 부릅니다. 앞에서 공간 방정식에 넣은 μₙ는 (nπ/L)²이고, 시간의 λₙ는 그 제곱근에 c를 곱한 값입니다. 그래서 계산할 때는 이름보다 “어느 방정식에 들어가는 수인가”를 확인하는 편이 안전합니다.', M(r"\mu_n=\left(\frac{n\pi}{L}\right)^2\quad\longrightarrow\quad\lambda_n=c\sqrt{\mu_n}"), 'Bₙ*의 별표는 두 번째 계수라는 표시입니다. Bₙ을 제곱하거나 켤레로 바꾸라는 연산이 아닙니다. Spectrum(스펙트럼)은 이 줄에 허용되는 λₙ들의 목록입니다.')
    ])

    add(10, '여러 모드를 합치고 초기조건으로 계수 구하기', [
      C('선형 중첩에서 Fourier sine series(푸리에 사인 급수)로', M(r"u(x,t)=\sum_{n=1}^{\infty}\left[B_n\cos(\lambda_nt)+B_n^*\sin(\lambda_nt)\right]\sin\frac{n\pi x}{L},\quad\lambda_n=\frac{cn\pi}{L}"), '각 항이 제차 PDE와 동차 경계조건을 만족하므로 유한합도 만족합니다. 무한합은 초기함수의 정칙성과 수렴에 맞는 해의 의미로 취합니다. 충분히 매끄러우면 고전해로, 삼각형처럼 모서리가 있으면 약한 의미와 조각별 고전해로 해석합니다.'),
      C('1 · 처음의 모양으로 Bₙ를 구합니다.', M(r"f(x)=u(x,0)=\sum_{n=1}^{\infty}B_n\sin\frac{n\pi x}{L}"), M(r"\int_0^L\sin\frac{n\pi x}{L}\sin\frac{m\pi x}{L}\,dx=\begin{cases}0,&n\ne m,\\L/2,&n=m,\end{cases}"), '양변에 sin(mπx/L)을 곱해 적분하면 orthogonality(직교성)로 m번째 항만 남습니다.', M(r"\int_0^Lf(x)\sin\frac{m\pi x}{L}\,dx=B_m\frac L2\quad\Rightarrow\quad\boxed{B_n=\frac2L\int_0^Lf(x)\sin\frac{n\pi x}{L}\,dx}")),
      C('2 · 처음의 속도로 Bₙ*를 구합니다.', M(r"u_t=\sum_{n=1}^{\infty}\lambda_n[-B_n\sin(\lambda_nt)+B_n^*\cos(\lambda_nt)]\sin\frac{n\pi x}{L}"), M(r"g(x)=\sum_{n=1}^{\infty}\lambda_nB_n^*\sin\frac{n\pi x}{L}\quad\Rightarrow\quad\boxed{B_n^*=\frac{2}{L\lambda_n}\int_0^Lg(x)\sin\frac{n\pi x}{L}\,dx}"), '초기속도의 사인 급수 계수는 Bₙ*가 아니라 λₙBₙ*입니다. 따라서 λₙ로 한 번 나누어야 합니다. 변위 단위인 Bₙ*는 속도 계수를 각주파수로 나누어 얻는다는 단위 검산도 가능합니다.'),
      C('편집자 추가 예제 · 초기속도가 있는 경우', 'f(x)=0, g(x)=v₀ sin(2πx/L)라면 Bₙ=0, B₂*=v₀/λ₂이고 나머지 Bₙ*=0입니다.', M(r"u(x,t)=\frac{v_0}{\lambda_2}\sin(\lambda_2t)\sin\frac{2\pi x}{L},\quad\lambda_2=\frac{2\pi c}{L}"), 't=0에서 변위는 0이지만 시간 미분은 주어진 v₀ sin(2πx/L)가 됩니다. 이 예가 1/λ₂를 빠뜨리면 안 되는 이유를 직접 보여 줍니다.')
    ], [
      C('1 · 줄의 처음 모양은 한 사인파로 맞지 않을 수 있습니다.', '삼각형이나 비대칭 모양을 한 개의 매끈한 사인 곡선으로 만들 수는 없습니다. 그래서 앞에서 구한 normal modes(정상모드)를 서로 다른 양만큼 섞습니다. 선형방정식에서는 맞는 해들을 더해도 해가 되기 때문에 가능한 전략입니다.', M(r"u=\sum_{n=1}^{\infty}[B_n\cos(\lambda_nt)+B_n^*\sin(\lambda_nt)]\sin(n\pi x/L)"), '이제 모양의 후보를 새로 찾는 대신 “각 재료를 얼마나 넣을까?”라는 coefficient(계수) 문제로 바뀝니다.'),
      C('2 · t=0을 넣으면 절반의 계수가 저절로 사라집니다.', 'cos 0=1이고 sin 0=0입니다. 그래서 처음 모양 f에는 Bₙ만 남습니다.', M(r"f(x)=u(x,0)=\sum_{n=1}^{\infty}B_n\sin\frac{n\pi x}{L}"), '이는 이전 단원에서 배운 Fourier sine series(푸리에 사인 급수)와 같습니다. m번째 재료의 양만 골라내려면 같은 사인을 곱해 0부터 L까지 적분합니다. 서로 다른 번호의 파동은 양수·음수가 상쇄되고 같은 번호의 사인 제곱은 L/2가 됩니다.', M(r"\int_0^Lf(x)\sin\frac{m\pi x}{L}\,dx=\frac L2 B_m\quad\Rightarrow\quad B_m=\frac2L\int_0^Lf(x)\sin\frac{m\pi x}{L}\,dx"), '이 상쇄 성질의 이름이 orthogonality(직교성)입니다. 앞 단원에서 계수를 적분으로 구했던 이유가 여기서 그대로 쓰입니다.'),
      C('3 · 속도를 맞추려면 먼저 시간으로 미분합니다.', 'u(x,0)만으로는 Bₙ*를 알 수 없었습니다. 이번에는 속도 uₜ를 구해 t=0을 넣습니다. 합성함수의 미분 때문에 cos(λₙt)를 미분하면 −λₙ sin(λₙt), sin(λₙt)를 미분하면 λₙ cos(λₙt)가 됩니다.', M(r"\begin{aligned}u_t(x,t)&=\sum_n[-\lambda_nB_n\sin(\lambda_nt)+\lambda_nB_n^*\cos(\lambda_nt)]\sin\frac{n\pi x}{L},\\g(x)=u_t(x,0)&=\sum_n\lambda_nB_n^*\sin\frac{n\pi x}{L}.\end{aligned}"), '이번에 뽑아낸 계수는 λₙBₙ*입니다. Bₙ*만 얻으려면 λₙ로 나눠야 합니다.', M(r"\lambda_n B_n^*=\frac2L\int_0^Lg(x)\sin\frac{n\pi x}{L}\,dx\quad\Rightarrow\quad B_n^*=\frac2{L\lambda_n}\int_0^Lg(x)\sin\frac{n\pi x}{L}\,dx")),
      C('4 · 두 계수가 맡은 일을 한 번에 확인합니다.', 'Bₙ는 처음부터 휘어 놓은 모양의 양이고, Bₙ*는 처음에 밀어 준 속도에서 정해지는 양입니다. 편집자 예로 처음 모양은 평평하고 g=v₀ sin(2πx/L)만 주면 두 번째 모드의 시간 사인만 남습니다.', M(r"u=\frac{v_0}{\lambda_2}\sin(\lambda_2t)\sin\frac{2\pi x}{L}\quad\Rightarrow\quad u(x,0)=0,\quad u_t(x,0)=v_0\sin\frac{2\pi x}{L}"), '공식을 외우기보다 t=0 대입과 시간 미분을 순서대로 하면 계수의 위치와 1/λₙ를 다시 만들 수 있습니다. 모서리가 있는 초기함수의 무한급수는 모든 점에서 두 번 미분할 수 있다고 단정하지 않고, 매끄러운 구간에서 PDE를 확인합니다.')
    ])

    add(12, '초기속도가 0인 줄 · 놓는 순간과 계속 정지는 다릅니다.', [
      C('g≡0이면 시간 사인항이 사라집니다.', M(r"g(x)=0\quad\Rightarrow\quad B_n^*=0\quad\Rightarrow\quad u(x,t)=\sum_{n=1}^{\infty}B_n\cos\frac{cn\pi t}{L}\sin\frac{n\pi x}{L}"), M(r"B_n=\frac2L\int_0^Lf(x)\sin\frac{n\pi x}{L}\,dx"), 'Initial velocity(초기속도)가 0이라는 것은 놓는 순간 정지해 있다는 뜻입니다. f가 휘어 있으면 복원력 때문에 이후에 움직입니다. f도 0일 때에만 이 고정단 무외력 문제의 영해를 얻습니다.'),
      C('편집자 추가 예제 · 한 모드로 놓으면', 'f(x)=h sin(πx/L), g=0이면 B₁=h만 남습니다.', M(r"u=h\sin\frac{\pi x}{L}\cos\frac{\pi ct}{L},\qquad u_{tt}(x,0)=-h\left(\frac{\pi c}{L}\right)^2\sin\frac{\pi x}{L}"), '처음 속도는 0이지만 h&gt;0일 때 위로 부푼 부분의 가속도는 아래쪽입니다. 시간 L/(2c)에는 줄이 수평선을 통과하고, L/c에는 반대 모양, 2L/c에는 처음 상태로 돌아옵니다.')
    ], [
      C('1 · 손을 가만히 놓아도 줄은 나중에 움직입니다.', '줄을 위로 당겼다가 밀지 않고 놓으면 initial velocity(초기속도) g는 0입니다. 그러나 팽팽한 줄은 펴지려는 힘을 받아 바로 가속합니다. 따라서 g=0을 “영원히 u=0”으로 읽으면 안 됩니다. 위치와 속도는 서로 다른 정보입니다.'),
      C('2 · 왜 코사인만 남는지 미분으로 확인합니다.', '앞 페이지에서 Bₙ*는 g의 적분으로 정했습니다. g가 0이면 그 적분도 0이므로 모든 Bₙ*=0입니다. 시간 코사인을 미분하면 사인이 되어 t=0에서 속도가 0이 됩니다.', M(r"u=\sum_n B_n\cos(\lambda_nt)\sin\frac{n\pi x}{L},\qquad u_t(x,0)=\sum_n-\lambda_nB_n\underbrace{\sin0}_{0}\sin\frac{n\pi x}{L}=0"), '남은 Bₙ는 처음 높이 f를 맞추는 Fourier coefficient(푸리에 계수)입니다.', M(r"B_n=\frac2L\int_0^Lf(x)\sin\frac{n\pi x}{L}\,dx")),
      C('3 · 편집자 예제 · 높이 h인 한 사인 모양', M(r"f(x)=h\sin\frac{\pi x}{L}\quad\Rightarrow\quad u(x,t)=h\sin\frac{\pi x}{L}\cos\frac{\pi ct}{L}"), 't=0이면 시간 코사인이 1, t=L/(2c)이면 0, t=L/c이면 −1입니다. 줄은 처음 모양 → 수평선 → 뒤집힌 모양으로 움직입니다. 수평선이 된 순간에는 높이만 0이지 속도가 0은 아닙니다. 공이 꼭대기에서 잠깐 멈춘 뒤 떨어지는 것처럼 “지금 속도가 0”과 “계속 정지”를 구분하십시오.')
    ])
