"""Complete solution of the original triangular pluck problem (p.21)."""
def populate(add, C, M, table):
    add(21, '연습문제 · 가운데를 높이 k만큼 당겨 놓은 줄', [
      C('원본 조건과 풀이 전략', M(r"\begin{gathered}u_{tt}=c^2u_{xx},\qquad u(0,t)=u(L,t)=0,\qquad u_t(x,0)=0,\\u(x,0)=f(x)=\begin{cases}\dfrac{2k}{L}x,&0<x<L/2,\\\dfrac{2k}{L}(L-x),&L/2<x<L.\end{cases}\end{gathered}"), 'L&gt;0,c&gt;0입니다. 원본의 두 식은 가운데에서 k로 만나므로 f(L/2)=k, 끝점은 f(0)=f(L)=0으로 연속적으로 정의합니다. k는 최고 변위이며 파수나 Fourier 계수가 아닙니다. 초기속도가 0이므로 Bₙ*=0이고, 초기변위의 사인 계수 Bₙ만 계산하면 됩니다. 아래는 원본에 없는 편집자 완성 풀이입니다.'),
      C('1 · 두 구간을 나누어 Fourier coefficient(푸리에 계수)를 적분합니다.', M(r"\begin{aligned}B_n&=\frac2L\int_0^L f(x)\sin\frac{n\pi x}{L}\,dx\\&=\frac{4k}{L^2}\left[\int_0^{L/2}x\sin(a_nx)\,dx+\int_{L/2}^{L}(L-x)\sin(a_nx)\,dx\right],\qquad a_n=\frac{n\pi}{L}.\end{aligned}"), '공식 앞의 2/L와 f의 2k/L를 곱해 4k/L²가 됩니다. f의 식이 바뀌는 L/2에서 적분도 나눕니다.'),
      C('2 · 부분적분의 경계항까지 계산합니다.', M(r"\int x\sin(ax)\,dx=-\frac{x\cos(ax)}a+\frac{\sin(ax)}{a^2}"), M(r"\int (L-x)\sin(ax)\,dx=-\frac{(L-x)\cos(ax)}a-\frac{\sin(ax)}{a^2}"), 'θ=nπ/2, a=aₙ로 두면 두 정적분은 다음과 같습니다. sin(nπ)=0을 사용했습니다.', M(r"\begin{aligned}I_1&=-\frac L{2a}\cos\theta+\frac{\sin\theta}{a^2},\\I_2&=\frac L{2a}\cos\theta+\frac{\sin\theta}{a^2},\\I_1+I_2&=\frac{2\sin\theta}{a^2}.\end{aligned}")),
      C('3 · 짝수 모드는 사라지고 홀수 모드의 부호가 번갈아 나옵니다.', M(r"\boxed{B_n=\frac{8k}{n^2\pi^2}\sin\frac{n\pi}{2}},\qquad B_n^*=0"), M(r"B_{2m}=0\ (m\ge1),\qquad B_{2m+1}=\frac{8k(-1)^m}{(2m+1)^2\pi^2}\ (m\ge0)"), '첫 계수는 B₁=8k/π², B₃=−8k/(9π²), B₅=8k/(25π²)입니다. 중앙 대칭 f(L−x)=f(x)와 sin[nπ(L−x)/L]=(−1)ⁿ⁺¹sin(nπx/L)로도 짝수 계수의 소멸을 확인할 수 있습니다.'),
      C('4 · 시간 진동을 붙이면 최종해입니다.', M(r"\boxed{u(x,t)=\frac{8k}{\pi^2}\sum_{m=0}^{\infty}\frac{(-1)^m}{(2m+1)^2}\sin\frac{(2m+1)\pi x}{L}\cos\frac{(2m+1)\pi ct}{L}}"), '각 항은 고정단과 파동방정식을 만족합니다. t=0에서 코사인이 1이 되어 f의 Fourier sine series(푸리에 사인 급수)가 됩니다. 초기속도 조건 g=0의 정확한 의미는 아래와 같이 구분합니다. f의 모서리가 있어 모든 점에서 2차 도함수가 존재하는 고전해는 아니며, 파동을 따라 움직이는 모서리를 제외한 영역에서 고전해이고 전체적으로는 약한 해로 이해합니다.', '정확한 정칙성: 초기속도 0은 L² 의미의 초기값으로 성립합니다. 뾰족한 점 x=L/2에서는 t=0의 점별 시간 미분과 무한급수의 항별 미분을 바꿀 수 없습니다. 실제 D’Alembert 해의 이 점에서 오른쪽 시간 미분은 −2kc/L입니다. 이 한 점의 차이는 L² 초기값을 바꾸지 않습니다.'),
      C('5 · 독립 검산 · 중앙값과 D’Alembert 표현', M(r"u(L/2,0)=\frac{8k}{\pi^2}\sum_{m=0}^{\infty}\frac1{(2m+1)^2}=\frac{8k}{\pi^2}\cdot\frac{\pi^2}{8}=k"), '여기서는 sin[(2m+1)π/2]=(−1)ᵐ가 계수의 부호와 곱해져 모든 항이 양수가 됩니다. 같은 해를 f의 홀수 2L-주기 연장 f̃로 쓰면 다음과 같습니다.', M(r"u(x,t)=\frac12[\widetilde f(x+ct)+\widetilde f(x-ct)]"), M(r"u(x,L/(2c))=0,\qquad u(x,L/c)=-f(x),\qquad u(x,2L/c)=f(x)"), 'L/(2c)에서 변위가 0인 것은 줄이 수평선을 통과한다는 뜻입니다. 운동이 끝나거나 에너지가 사라진 것은 아닙니다. 아래 비교 그림은 유한 급수와 연장 공식을 서로 독립적으로 계산합니다.')
    ], [
      C('1 · 문제 문장부터 줄의 그림으로 바꿉니다.', '양 끝은 높이 0, 가운데는 높이 k입니다. 왼쪽 절반은 기울기 2k/L로 올라가고 오른쪽 절반은 같은 크기의 기울기로 내려옵니다. 가만히 놓았으므로 initial velocity(초기속도)는 0입니다. c는 파동 속도, L은 줄 길이, k는 당긴 높이입니다.', M(r"f(x)=\begin{cases}(2k/L)x,&0\le x\le L/2,\\(2k/L)(L-x),&L/2\le x\le L.\end{cases}"), '원본은 열린 구간으로 적었지만 양쪽 식의 가운데 값은 모두 k입니다. 끝점과 중앙점의 값을 연속적으로 채워 썼습니다. 이후의 모든 계산은 이 원본 문제를 푼 편집자 해설입니다.'),
      C('2 · 이미 구한 해 틀에서 필요한 부분만 남깁니다.', '양 끝 고정인 줄의 공간 모양은 sin(nπx/L)입니다. 초기속도가 0이면 시간 사인항 Bₙ*는 모두 0이므로 코사인만 남습니다. 이제 아직 모르는 것은 각 공간 사인을 얼마나 섞을지 나타내는 Bₙ입니다.', M(r"u(x,t)=\sum_{n=1}^{\infty}B_n\cos\frac{cn\pi t}{L}\sin\frac{n\pi x}{L},\qquad B_n=\frac2L\int_0^Lf(x)\sin\frac{n\pi x}{L}\,dx"), '이 공식은 10쪽에서 같은 번호의 사인을 곱하고 적분하는 orthogonality(직교성)로 유도했습니다. 여기서는 그 f 자리에 삼각형의 두 식을 넣습니다.'),
      C('3 · 적분을 중간에서 나누는 이유', '0부터 L/2까지는 f=(2k/L)x이고 그다음은 f=(2k/L)(L−x)입니다. 같은 하나의 식을 전 구간에 쓰면 다른 모양을 풀게 됩니다. 먼저 나눈 뒤 공통 상수를 밖으로 꺼냅니다.', M(r"B_n=\frac{4k}{L^2}\left[\underbrace{\int_0^{L/2}x\sin(a x)\,dx}_{I_1}+\underbrace{\int_{L/2}^L(L-x)\sin(a x)\,dx}_{I_2}\right],\quad a=\frac{n\pi}{L}"), '새 문자 a는 긴 nπ/L을 잠깐 줄인 것입니다. 마지막에는 다시 넣습니다. 앞의 4k/L²는 (2/L)×(2k/L)입니다.'),
      C('4 · 왼쪽 적분은 곱의 미분을 거꾸로 씁니다.', 'Integration by parts(부분적분) ∫p q′=pq−∫p′q에서 p=x, q′=sin(ax)를 택합니다. x는 미분하면 1로 단순해지고, 사인은 적분할 수 있기 때문입니다. sin(ax)의 원시함수는 −cos(ax)/a입니다.', M(r"\begin{aligned}\int x\sin(ax)\,dx&=-\frac{x\cos(ax)}a+\frac1a\int\cos(ax)\,dx\\&=-\frac{x\cos(ax)}a+\frac{\sin(ax)}{a^2}.\end{aligned}"), M(r"I_1=\left[-\frac{x\cos(ax)}a+\frac{\sin(ax)}{a^2}\right]_0^{L/2}=-\frac L{2a}\cos\frac{n\pi}{2}+\frac1{a^2}\sin\frac{n\pi}{2}"), '아래끝 x=0에서는 두 항이 모두 0입니다. 위끝에서는 aL/2=nπ/2가 됩니다.'),
      C('5 · 오른쪽 적분에서는 L−x의 미분 부호를 지킵니다.', '(L−x)를 미분하면 −1입니다. 이것 때문에 원시함수의 두 번째 항이 왼쪽 적분과 반대 부호가 됩니다.', M(r"\int(L-x)\sin(ax)\,dx=-\frac{(L-x)\cos(ax)}a-\frac{\sin(ax)}{a^2}"), '위끝 x=L에서는 L−x=0이고 sin(aL)=sin(nπ)=0이므로 값이 0입니다. 아래끝 x=L/2의 값을 빼면 부호가 다시 바뀝니다.', M(r"\begin{aligned}I_2&=0-\left[-\frac L{2a}\cos\frac{n\pi}{2}-\frac1{a^2}\sin\frac{n\pi}{2}\right]\\&=\frac L{2a}\cos\frac{n\pi}{2}+\frac1{a^2}\sin\frac{n\pi}{2}.\end{aligned}")),
      C('6 · 두 적분을 더하면 복잡한 항이 지워집니다.', 'I₁에는 −L cos(nπ/2)/(2a), I₂에는 +L cos(nπ/2)/(2a)가 있으므로 상쇄됩니다. 같은 사인항 두 개만 남습니다.', M(r"I_1+I_2=\frac2{a^2}\sin\frac{n\pi}{2}\quad\Rightarrow\quad B_n=\frac{4k}{L^2}\frac2{(n\pi/L)^2}\sin\frac{n\pi}{2}=\frac{8k}{n^2\pi^2}\sin\frac{n\pi}{2}"), '이것으로 모든 coefficient(계수)를 계산했습니다. n=1,2,3,4,5를 넣으면 사인값이 1,0,−1,0,1입니다. 따라서 짝수 번호는 빠지고 홀수 번호만 번갈아 부호를 가집니다.', M(r"B_1=\frac{8k}{\pi^2},\quad B_2=0,\quad B_3=-\frac{8k}{9\pi^2},\quad B_4=0,\quad B_5=\frac{8k}{25\pi^2}")),
      C('7 · 구한 계수를 처음의 해 틀에 넣습니다.', M(r"\begin{aligned}u(x,t)=\frac{8k}{\pi^2}\bigg[&\sin\frac{\pi x}{L}\cos\frac{\pi ct}{L}-\frac19\sin\frac{3\pi x}{L}\cos\frac{3\pi ct}{L}\\&+\frac1{25}\sin\frac{5\pi x}{L}\cos\frac{5\pi ct}{L}-\cdots\bigg].\end{aligned}"), '홀수 번호를 2m+1이라고 쓰면 같은 답을 한 줄의 합으로 적을 수 있습니다. m=0,1,2,…를 넣으면 1,3,5,…이고 (−1)ᵐ가 +,−,+,…를 만듭니다.', M(r"\boxed{u(x,t)=\frac{8k}{\pi^2}\sum_{m=0}^{\infty}\frac{(-1)^m}{(2m+1)^2}\sin\frac{(2m+1)\pi x}{L}\cos\frac{(2m+1)\pi ct}{L}}")),
      C('8 · 답이 조건을 지키는지 하나씩 확인합니다.', 'x=0,L에서는 공간 사인이 0이므로 양 끝이 고정됩니다. t=0에서는 시간 코사인이 1이 되어 처음 삼각형의 사인 급수가 됩니다. 유한 개 항의 시간 미분은 t=0에서 0이며, 전체 해도 아래에 설명하는 초기값의 의미에서 g=0을 만족합니다. 가운데에서는 공간 사인의 번갈아 나오는 부호와 계수의 부호가 곱해져 전부 양수가 됩니다.', M(r"u(L/2,0)=\frac{8k}{\pi^2}\left(1+\frac19+\frac1{25}+\cdots\right)=k"), '괄호의 합은 π²/8입니다. 앞의 계수 8이나 π²를 잘못 쓰면 최고 높이 검산이 실패합니다. 처음 모양에 뾰족한 꼭짓점이 있으므로 모든 점에서 매끄럽게 두 번 미분할 수 있는 것은 아닙니다. 모서리가 이동하는 선 밖에서는 보통의 미분으로 PDE가 성립하고, 전체 해는 약한 의미로 받아들입니다.', '더 엄밀하게는 중앙의 딱 한 점에서 처음 속도를 점별 미분으로 0이라 할 수 없습니다. D’Alembert 해를 보면 작은 양의 t에 중앙 높이는 k−2kct/L이므로 그 순간 오른쪽 시간 미분은 −2kc/L입니다. 이 문제의 g=0은 “속도 오차의 제곱을 줄 전체에서 적분한 값이 t→0일 때 0이 된다”는 L² 초기값으로 해석합니다. 지금은 뾰족한 점에서 무한합을 마음대로 미분하지 않는다는 구별을 기억하면 됩니다.'),
      C('9 · 다른 방법으로 같은 움직임을 봅니다.', 'D’Alembert formula(달랑베르 공식)에서는 삼각형을 홀수 2L-주기 연장한 f̃를 좌우로 옮겨 평균냅니다. 초기속도가 0이므로 적분항은 없습니다.', M(r"u(x,t)=\frac12[\widetilde f(x+ct)+\widetilde f(x-ct)]"), 't=L/(2c)에는 전체 높이가 0이 되지만 줄은 수평선을 통과하는 중입니다. t=L/c에는 삼각형이 아래로 뒤집히고 t=2L/c에는 처음 상태로 돌아옵니다. 아래에서 시간을 옮기면 이 과정을 볼 수 있습니다. 급수의 항 수를 늘리면 모서리 부근의 근사도 좋아집니다.')
    ], role='원본 연습문제 · 전체 풀이')
