"""Every source practice problem, including ambiguous source statements."""
def populate(add, C, M, table):
    add(11, '연습 1 · 지수함수의 변환으로 이상적분 구하기', [
        C('원문 문제와 변환 계산', '원문은 x&gt;0에서 f(x)=e⁻ᵏˣ, k&gt;0을 사용해 아래 두 적분을 구하라는 문제입니다. 두 번째 적분의 분자에는 ω가 없습니다. 이 조건을 그대로 유지합니다.', M(r"I_c(x)=\int_0^\infty\frac{\cos(\omega x)}{k^2+\omega^2}\,d\omega,\qquad J(x)=\int_0^\infty\frac{\sin(\omega x)}{k^2+\omega^2}\,d\omega"), M(r"\begin{aligned}\int_0^\infty e^{-kt}\cos(\omega t)\,dt&=\frac{k}{k^2+\omega^2},\\\int_0^\infty e^{-kt}\sin(\omega t)\,dt&=\frac{\omega}{k^2+\omega^2},\\C[e^{-kt}]&=\sqrt{\frac2\pi}\frac{k}{k^2+\omega^2},\qquad S[e^{-kt}]=\sqrt{\frac2\pi}\frac{\omega}{k^2+\omega^2}.\end{aligned}")),
        C('코사인 적분의 완성 풀이', M(r"e^{-kx}=\frac{2k}{\pi}\int_0^\infty\frac{\cos(\omega x)}{k^2+\omega^2}\,d\omega\quad\Longrightarrow\quad I_c(x)=\frac{\pi}{2k}e^{-kx}\quad(x>0)"), 'x=0에서도 π/(2k)이며, 실수 전체의 식은 πe⁻ᵏ|ˣ|/(2k)입니다. 사인 역변환이 바로 주는 것은 다음의 관련 적분입니다. 이것을 원문의 J와 혼동하지 않습니다.', M(r"\int_0^\infty\frac{\omega\sin(\omega x)}{k^2+\omega^2}\,d\omega=\frac\pi2e^{-kx}\qquad(x>0)")),
        C('분자에 ω가 없는 원문 사인 적분', M(r"\boxed{J(x)=\frac{e^{-kx}\operatorname{Ei}(kx)-e^{kx}\operatorname{Ei}(-kx)}{2k}\quad(k>0,\ x>0)}"), 'Ei는 exponential integral(지수적분 함수)입니다. 초등함수만으로 닫히는 앞의 적분과 달리 특수함수가 나타납니다. 원문 식이 적분 자체로 잘못된 것은 아니며, 주어진 지수함수의 사인 역변환에서 즉시 나오지 않는다는 차이입니다.', M(r"\operatorname{Ei}(z)=\operatorname{PV}\int_{-\infty}^{z}\frac{e^u}{u}\,du\quad(z\ne0)"), 'PV는 0 양옆의 같은 폭을 제외한 뒤 함께 극한을 취하는 Cauchy principal value(코시 주값)입니다. z&lt;0에서는 구간에 0이 없으므로 통상적인 적분입니다.'),
        C('원문 사인 적분의 유도 · 심화 보강', M(r"\frac1{k^2+\omega^2}=\frac1k\int_0^\infty e^{-kt}\cos(\omega t)\,dt"), '이 표현을 J에 넣되 e⁻ᵋω, ε&gt;0을 곱해 먼저 절대수렴시키고 적분 순서를 바꿉니다. sin A cos B=(sin(A+B)+sin(A−B))/2와 ∫₀∞e⁻ᵋωsin(bω)dω=b/(ε²+b²)를 적용한 뒤 ε→0⁺를 취합니다.', M(r"J(x)=\frac1{2k}\left[\int_0^\infty\frac{e^{-kt}}{x+t}\,dt+\operatorname{PV}\int_0^\infty\frac{e^{-kt}}{x-t}\,dt\right]"), M(r"\begin{aligned}\int_0^\infty\frac{e^{-kt}}{x+t}\,dt&=-e^{kx}\operatorname{Ei}(-kx),\\\operatorname{PV}\int_0^\infty\frac{e^{-kt}}{x-t}\,dt&=e^{-kx}\operatorname{Ei}(kx).\end{aligned}"), '첫 적분에는 u=−k(x+t), 둘째에는 u=k(x−t)를 대입합니다. 두 결과를 합하면 상자의 답입니다. k=x=1에서 J≈0.64676112이며, ω가 있는 관련 적분의 값 π/(2e)≈0.57786367과 다릅니다.')
    ], [
        C('1 · 무엇을 구하라는 문제인지 구별합니다.', '문제에는 코사인 적분과 사인 적분이 나란히 있습니다. 분모는 둘 다 k²+ω²이고, 분자는 각각 cos(ωx), sin(ωx)입니다. k는 양의 상수, x는 값을 알고 싶은 위치, ω는 적분하면서 사라질 변수입니다.', M(r"I_c(x)=\int_0^\infty\frac{\cos(\omega x)}{k^2+\omega^2}\,d\omega,\qquad J(x)=\int_0^\infty\frac{\sin(\omega x)}{k^2+\omega^2}\,d\omega")),
        C('2 · 왜 e⁻ᵏᵗ를 먼저 변환할까요?', '적분을 바로 풀기 어려울 때는 이미 아는 함수의 복원식 속에 같은 적분이 숨어 있는지 찾습니다. 지수함수와 삼각함수를 곱해 적분하면 k²+ω²라는 분모가 생기므로 좋은 출발점입니다.', M(r"\int e^{-kt}\cos(\omega t)\,dt=\frac{e^{-kt}[-k\cos(\omega t)+\omega\sin(\omega t)]}{k^2+\omega^2}"), '위끝 t→∞에서는 e⁻ᵏᵗ가 0으로 갑니다. 아래끝 t=0에서는 분자가 −k입니다. 위끝에서 아래끝을 빼면 k/(k²+ω²)가 됩니다. 이것에 √(2/π)를 곱한 것이 cosine transform(코사인 변환)입니다.'),
        C('3 · 역변환식을 목표 적분에 맞게 정리합니다.', M(r"e^{-kx}=\sqrt{\frac2\pi}\int_0^\infty\left[\sqrt{\frac2\pi}\frac{k}{k^2+\omega^2}\right]\cos(\omega x)\,d\omega=\frac{2k}{\pi}I_c(x)"), '두 개의 √(2/π)를 곱하면 2/π입니다. k도 적분변수 ω와 무관하므로 밖으로 나옵니다. 양변을 2k/π로 나누면 답을 얻습니다.', M(r"\boxed{I_c(x)=\frac\pi{2k}e^{-kx}\quad(x>0)}")),
        C('4 · 사인에서는 분자가 달라집니다.', M(r"S[e^{-kt}]=\sqrt{\frac2\pi}\frac{\omega}{k^2+\omega^2}\quad\Longrightarrow\quad\int_0^\infty\frac{\omega\sin(\omega x)}{k^2+\omega^2}\,d\omega=\frac\pi2e^{-kx}"), '이 결과의 분자에는 ω가 있습니다. ω는 적분하면서 변하는 값이므로, 적분 밖에서 ω로 나누어 지울 수 없습니다. 따라서 이 식을 원문의 사인 적분 답으로 옮겨 적으면 다른 문제를 푼 셈이 됩니다.'),
        C('5 · 원문 그대로의 답은 새로운 함수 이름을 사용합니다.', '삼각함수만으로 모든 적분을 표현할 수는 없습니다. 여기서는 특정 적분에 exponential integral(지수적분 함수), Ei라는 이름을 붙입니다. 지금은 새로운 공식 전체를 외우기보다 “이 문제는 기본 사인 역변환만으로 끝나지 않는다”는 사실부터 구분하십시오.', M(r"\operatorname{Ei}(z)=\operatorname{PV}\int_{-\infty}^{z}\frac{e^u}{u}\,du,\qquad J(x)=\frac{e^{-kx}\operatorname{Ei}(kx)-e^{kx}\operatorname{Ei}(-kx)}{2k}"), '양의 z에서는 적분 경로가 0을 지나므로 0 양쪽을 같은 폭으로 제외했다가 함께 좁히는 주값을 사용합니다. 원래 J 적분에는 분모 k²+ω²가 0이 되는 점이 없어 이런 특이점이 없습니다. 주값은 답을 Ei로 표현하는 중간 계산에서 등장합니다.'),
        C('6 · 그 답이 나오는 계산도 확인합니다.', '분모를 지수함수의 코사인 적분으로 바꾼 뒤, 수렴을 위한 작은 감쇠 e⁻ᵋω를 넣습니다. 곱-합 공식으로 사인 두 개가 생기고 그 적분은 b/(ε²+b²)입니다. ε를 0으로 보내면 아래 식이 나옵니다.', M(r"J(x)=\frac1{2k}\left[\int_0^\infty\frac{e^{-kt}}{x+t}\,dt+\operatorname{PV}\int_0^\infty\frac{e^{-kt}}{x-t}\,dt\right]"), '첫 항은 u=−k(x+t)로 치환하여 −eᵏˣEi(−kx), 둘째 항은 u=k(x−t)로 치환하여 e⁻ᵏˣEi(kx)가 됩니다. 두 항의 합에 1/(2k)를 곱하면 위 답입니다. 이 마지막 유도는 심화 보강이며, 코사인 역변환의 사용법과 두 사인 적분의 차이를 먼저 익히면 됩니다.', '편집자 검산: k=x=1이면 원문 J≈0.64676112, 분자에 ω가 있는 식은 약 0.57786367입니다. 식이 비슷하다고 값까지 같지는 않습니다.')
    ], role='연습문제·완성 풀이', audit='원본 두 번째 적분의 분자는 sin(ωx)이며 ω가 곱해져 있지 않습니다. 원문 J의 특수함수 답과, 지수함수의 사인 역변환에서 나오는 ωsin(ωx) 적분을 따로 풀이합니다. 출제자가 ω를 빠뜨렸다고 단정하지 않습니다.')

    add(12, '연습 1의 원본 빈 풀이 페이지', [C('원본 페이지 보존', '원본에는 이 페이지의 풀이가 적혀 있지 않습니다. 코사인 적분, 원문 사인 적분, 관련 사인 역변환의 완성 풀이를 모두 <a href="#slide-11">11쪽 해설</a>에 수록했습니다.', kind='quiet-card')], role='빈 풀이 공간')

    add(13, '연습 2 · 반구간 직사각 펄스의 두 변환', [
        C('원문과 계산 구간', M(r"f(x)=\begin{cases}k,&0<x<a,\\0,&x>a,\end{cases}\qquad a>0"), '높이 k, 폭 a의 반구간 펄스입니다. 적분에서 점 하나의 값은 결과에 영향을 주지 않으며, 불연속점의 복원값은 따로 처리합니다.'),
        C('Cosine transform(코사인 변환)', M(r"C[f](\omega)=\sqrt{\frac2\pi}k\int_0^a\cos(\omega x)\,dx=\sqrt{\frac2\pi}\frac{k\sin(a\omega)}{\omega},\qquad C[f](0)=\sqrt{\frac2\pi}ka")),
        C('Sine transform(사인 변환)', M(r"S[f](\omega)=\sqrt{\frac2\pi}k\left[-\frac{\cos(\omega x)}{\omega}\right]_0^a=\sqrt{\frac2\pi}\frac{k[1-\cos(a\omega)]}{\omega},\qquad S[f](0)=0"), 'x=a에서 두 역변환의 극한은 k/2입니다. x=0에서는 짝연장은 k, 홀연장은 좌우값 −k와 k의 평균 0으로 복원됩니다. 반구간 내부의 함수는 같아도 연장 방식의 경계값은 다릅니다.')
    ], [
        C('1 · 적분할 때 남는 부분은 어디인가요?', '원본은 0부터 a까지만 높이 k이고, 그 뒤는 0인 함수입니다. 변환 공식의 적분 상한은 ∞이지만 a 뒤의 곱은 모두 0입니다. 따라서 ∫₀∞를 ∫₀ᵃ로 줄일 수 있습니다. 이것이 조각별 함수 문제에서 가장 먼저 할 정리입니다.'),
        C('2 · 코사인 쪽은 사인으로 적분합니다.', M(r"C[f](\omega)=\sqrt{\frac2\pi}k\left[\frac{\sin(\omega x)}\omega\right]_0^a=\sqrt{\frac2\pi}k\frac{\sin(a\omega)-\sin0}\omega=\sqrt{\frac2\pi}\frac{k\sin(a\omega)}\omega"), 'a는 원본 펄스의 폭이고 ω는 변환 뒤의 주파수 변수입니다. 둘을 섞지 마십시오. 이 계산 동안 k, a, ω는 모두 상수로 취급하고 x만 적분합니다.'),
        C('3 · 사인 쪽의 음수 두 개를 확인합니다.', M(r"S[f](\omega)=\sqrt{\frac2\pi}k\left[-\frac{\cos(\omega x)}\omega\right]_0^a=\sqrt{\frac2\pi}k\frac{-\cos(a\omega)+\cos0}\omega=\sqrt{\frac2\pi}\frac{k[1-\cos(a\omega)]}\omega"), 'sine(사인)의 원시함수에는 −cos가 들어갑니다. 아래끝을 빼면 −(−cos 0)=+1이 되므로, 분자는 1−cos(aω)입니다. 부호를 감으로 기억하지 말고 위끝−아래끝을 펼치면 안전합니다.'),
        C('4 · ω=0은 따로 대입해야 합니다.', '답의 분모에 ω가 있으므로 완성식에 0을 넣으면 0/0처럼 보입니다. 그러나 원래 적분에는 문제가 없습니다. 코사인은 cos 0=1이므로 펄스의 넓이 ka를 세고, 사인은 sin 0=0이므로 0을 줍니다.', M(r"C[f](0)=\sqrt{\frac2\pi}ka,\qquad S[f](0)=0"), '따라서 변환 함수의 0에서의 값은 위 값으로 연속적으로 이어집니다. ω로 나누는 공식을 얻을 때 빠뜨린 예외를 다시 채운 것입니다.')
    ], role='연습문제·완성 풀이')

    add(14, '연습 3 · 지수 감쇠의 코사인 변환', [
        C('문제와 목표', M(r"f(x)=e^{-ax}\quad(x>0,\ a>0),\qquad C[f](\omega)=\sqrt{\frac2\pi}I,\quad I=\int_0^\infty e^{-ax}\cos(\omega x)\,dx"), 'a&gt;0은 무한대에서 지수함수와 경계항이 0으로 가도록 하는 조건입니다.'),
        C('부분적분 두 번으로 I를 풀기', M(r"\begin{aligned}I&=\left[-\frac1ae^{-ax}\cos(\omega x)\right]_0^\infty-\frac\omega a\int_0^\infty e^{-ax}\sin(\omega x)\,dx=\frac1a-\frac\omega aK,\\K&=\left[-\frac1ae^{-ax}\sin(\omega x)\right]_0^\infty+\frac\omega a I=\frac\omega a I,\\I&=\frac1a-\frac{\omega^2}{a^2}I\quad\Longrightarrow\quad I=\frac{a}{a^2+\omega^2}.\end{aligned}")),
        C('정규화와 검산', M(r"\boxed{C[e^{-ax}](\omega)=\sqrt{\frac2\pi}\frac{a}{a^2+\omega^2}}"), 'ω=0이면 √(2/π)/a로서 원래 함수의 넓이에 √(2/π)를 곱한 값입니다. a가 크면 원래 함수가 빨리 감소해 넓이는 작아지지만, 주파수 분포는 더 넓어집니다.')
    ], [
        C('1 · 정답에서 √(2/π)가 필요한 이유', '문제는 단순 적분 I가 아니라 cosine transform(코사인 변환)을 묻습니다. 변환의 정의는 적분 앞에 √(2/π)를 붙입니다. 먼저 적분 I만 구하고 마지막에 이 상수를 곱하면 계산이 덜 복잡합니다.', M(r"I=\int_0^\infty e^{-ax}\cos(\omega x)\,dx,\qquad C[f]=\sqrt{\frac2\pi}I")),
        C('2 · 곱의 적분을 한 번에 못 하면 관계식을 만듭니다.', 'e⁻ᵃˣ와 cos(ωx)의 곱은 각각의 적분을 곱해서 구할 수 없습니다. integration by parts(부분적분)를 사용하여 지수함수는 적분하고 코사인은 미분합니다. 그러면 사인 적분 K가 나타납니다.', M(r"I=\frac1a-\frac\omega aK,\qquad K=\int_0^\infty e^{-ax}\sin(\omega x)\,dx"), '첫 항 1/a는 경계값입니다. 위끝은 0이고 아래끝은 −1/a이므로 둘을 빼서 +1/a가 됩니다.'),
        C('3 · K에도 같은 계산을 하면 I로 되돌아옵니다.', M(r"K=\left[-\frac1ae^{-ax}\sin(\omega x)\right]_0^\infty+\frac\omega aI=\frac\omega aI"), '이번 경계값은 sin 0=0 때문에 사라집니다. 적분을 두 번 했는데 처음의 I가 다시 나왔습니다. 실패가 아니라, I를 미지수처럼 풀 수 있는 식을 얻은 것입니다.'),
        C('4 · 이제 고등학교의 방정식 정리입니다.', M(r"I=\frac1a-\frac{\omega^2}{a^2}I\ \Longrightarrow\ \left(1+\frac{\omega^2}{a^2}\right)I=\frac1a\ \Longrightarrow\ I=\frac{a}{a^2+\omega^2}"), M(r"\boxed{C[f](\omega)=\sqrt{\frac2\pi}\frac{a}{a^2+\omega^2}}"), 'I가 있는 항을 왼쪽에 모으고 괄호로 나눴습니다. 마지막에 변환의 상수를 붙이면 풀이가 끝납니다. ω=0을 넣으면 √(2/π)/a이며, e⁻ᵃˣ의 넓이 1/a와도 맞습니다.')
    ], role='연습문제·완성 풀이')

    add(34, '연습 4 · xe⁻ˣ²의 푸리에 변환', [
        C('원문 조건과 사용할 규약', M(r"f(x)=xe^{-x^2},\qquad F(\omega)=\frac1{\sqrt{2\pi}}\int_{-\infty}^\infty f(x)e^{-i\omega x}\,dx"), '원본은 함수만 제시합니다. 여기서는 p.17의 대칭 정규화를 사용합니다. 먼저 Gaussian(가우스 함수) g(x)=e⁻ˣ²의 변환 G를 구한 뒤, f=−g′/2를 이용합니다.'),
        C('가우스 함수의 변환 유도', M(r"G'(\omega)=\frac1{\sqrt{2\pi}}\int_{-\infty}^{\infty}(-ix)e^{-x^2}e^{-i\omega x}\,dx=\frac i2\mathcal F[g'](\omega)=\frac i2(i\omega G)=-\frac\omega2G"), '가우스 감쇠 때문에 미분과 적분의 교환 및 무한대 경계항 소멸이 정당합니다. 이 미분방정식을 풀면 G(ω)=Ke⁻ω²/4입니다.', M(r"G(0)=\frac1{\sqrt{2\pi}}\int_{-\infty}^\infty e^{-x^2}\,dx=\frac1{\sqrt2}\quad\Longrightarrow\quad G(\omega)=\frac1{\sqrt2}e^{-\omega^2/4}")),
        C('가우스 적분의 상수도 확인하기', '편집자 보강: I=∫ℝe⁻ˣ²dx라 두면 I&gt;0입니다. 곱을 평면 적분으로 바꾸고 polar coordinates(극좌표)를 쓰면 다음과 같습니다. 면적 요소가 r dr dθ가 되는 것은 반지름 r에서 부채꼴 띠의 길이가 r dθ이기 때문입니다.', M(r"I^2=\iint_{\mathbb R^2}e^{-(x^2+y^2)}\,dx\,dy=\int_0^{2\pi}\int_0^\infty e^{-r^2}r\,dr\,d\theta=2\pi\cdot\frac12=\pi,\qquad I=\sqrt\pi")),
        C('최종 답과 성질 검산', M(r"f=-\frac12g'\quad\Longrightarrow\quad\boxed{F(\omega)=-\frac{i\omega}{2\sqrt2}e^{-\omega^2/4}}"), 'f는 실수 odd function(홀함수)이므로 변환은 순허수 홀함수입니다. 답은 F(0)=0이고 F(−ω)=−F(ω)=F(ω)의 켤레를 만족합니다. 원본에는 풀이가 없으며 위 유도는 편집자 작성입니다.')
    ], [
        C('1 · x가 하나 붙은 이유를 미분으로 찾습니다.', '원문 함수는 xe⁻ˣ²입니다. 곧바로 복소 지수까지 곱해 적분하려면 어려워집니다. 대신 e⁻ˣ²를 미분해 보면 연쇄법칙에 의해 −2x가 붙습니다. 따라서 구하려는 함수는 그 도함수의 −1/2배입니다.', M(r"g(x)=e^{-x^2},\qquad g'(x)=-2xe^{-x^2},\qquad f(x)=-\frac12g'(x)")),
        C('2 · 먼저 G를 알고 싶습니다.', 'G는 g의 Fourier transform(푸리에 변환)입니다. G의 식을 모른다고 멈출 필요는 없습니다. G를 주파수 ω로 미분하면 e⁻ⁱωˣ에서 −ix가 나오므로, 다시 g′와 연결됩니다. 같은 함수를 두 가지 방법으로 표현하는 것이 핵심입니다.', M(r"G'(\omega)=\mathcal F[-ixg]=\frac i2\mathcal F[g']=\frac i2(i\omega G)=-\frac\omega2G"), '여기서 G′는 변환 결과를 ω로 미분한 것이고, ℱ[g′]는 원래 함수를 x로 미분한 뒤 변환한 것입니다. 모양은 비슷해도 서로 다른 연산입니다.'),
        C('3 · 미분하면 −ω/2배가 되는 함수', 'e⁻ω²/4를 ω로 미분하면 정확히 −ω/2가 앞에 곱해집니다. 따라서 G=Ke⁻ω²/4 형태입니다. 남은 K는 ω=0일 때의 값으로 구합니다.', M(r"G(0)=\frac1{\sqrt{2\pi}}\int_{-\infty}^{\infty}e^{-x^2}\,dx=\frac{\sqrt\pi}{\sqrt{2\pi}}=\frac1{\sqrt2}")),
        C('4 · √π라는 넓이는 어디서 왔나요?', 'Gaussian integral(가우스 적분)의 값입니다. 한 줄의 넓이 I를 자기 자신과 곱하면 평면 전체에서 e⁻⁽ˣ²⁺ʸ²⁾를 더하는 문제가 됩니다. 이 함수는 중심에서 거리 r만으로 값이 정해지므로, 동심원 모양의 얇은 띠로 더할 수 있습니다. 띠의 넓이는 둘레 2πr에 두께 dr을 곱한 것입니다.', M(r"I^2=\int_0^\infty e^{-r^2}2\pi r\,dr=\pi\int_0^\infty e^{-u}\,du=\pi\quad(u=r^2)"), 'I는 양수이므로 I=√π입니다. 이 부분은 이중적분의 기초를 보강한 설명이며, 이후에는 ∫ℝe⁻ˣ²dx=√π를 표준 적분으로 사용해도 됩니다.'),
        C('5 · 처음 목표로 돌아와 −1/2와 iω를 곱합니다.', M(r"G=\frac1{\sqrt2}e^{-\omega^2/4},\qquad F=-\frac12(i\omega G)=\boxed{-\frac{i\omega}{2\sqrt2}e^{-\omega^2/4}}"), '도함수를 변환하면 iω를 곱한다는 p.20의 성질을 썼습니다. 원래 함수는 좌우 부호가 반대인 실수 홀함수입니다. 따라서 cos 부분은 상쇄되고 −i sin 부분만 남아야 합니다. 답이 순허수이고 ω의 부호에 따라 반전되는지 확인하면 i와 음수의 실수를 잡을 수 있습니다.')
    ], role='연습문제·완성 풀이')

    add(35, '연습 4의 원본 빈 풀이 페이지', [C('원본 페이지 보존', '원본에는 별도 풀이가 없습니다. 가우스 적분부터 xe⁻ˣ²의 변환까지 <a href="#slide-34">34쪽의 완성 풀이</a>에 연결했습니다.', kind='quiet-card')], role='빈 풀이 공간')

    add(36, '연습 5 · e⁻ᵃω/ω의 역변환 조건 검토', [
        C('원문을 그대로 읽기', M(r"\text{Find }f(x)\text{ if its Fourier transform is }\frac{e^{-a\omega}}{\omega}."), '원본은 Fourier transform(푸리에 변환)이라고만 적고, a의 범위·주파수의 정의역·주값 여부를 지정하지 않습니다. |ω|나 i도 적혀 있지 않습니다. 앞에서 정의한 실수 전체의 복소 푸리에 변환으로 읽으면 보통의 역변환 문제로 성립하지 않습니다.'),
        C('일반적인 역변환이 성립하지 않는 이유', M(r"f(x)\stackrel{?}{=}\frac1{\sqrt{2\pi}}\int_{-\infty}^{\infty}\frac{e^{-a\omega}}{\omega}e^{i\omega x}\,d\omega"), 'ω=0 근처에서 적분함수는 1/ω처럼 되어 통상적인 이상적분은 발산합니다. 보통의 감쇠 상수 a&gt;0을 가정해도 ω→−∞에서는 e⁻ᵃω가 지수적으로 커집니다. 원점에 주값만 붙이는 것으로 이 꼬리 발산이 해결되지 않습니다. 실수 a&lt;0이면 반대 꼬리가 커집니다.', M(r"f\in L^1(\mathbb R)\ \Longrightarrow\ |F(\omega)|\leq\frac{\|f\|_1}{\sqrt{2\pi}}"), '또한 이 단원의 절대적분 가능한 f의 변환은 유계·연속이므로 1/ω 극점을 가진 원문 식이 될 수 없습니다. a=0도 통상적인 역적분은 성립하지 않으며, 분포·주값 해석은 별도의 규약이 필요합니다. 따라서 원문 그대로의 답은 “통상적인 변환의 범위에서 해가 없으며 추가 조건이 필요하다”입니다.'),
        C('조건을 추가한 별도 문제 · 사인 역변환이라면', '아래는 원문 정답을 추정한 것이 아니라, 비교를 위한 편집자 보강입니다. 만약 양의 주파수의 sine transform(사인 변환)이 S[f](ω)=e⁻ᵃω/ω이고 a&gt;0이라는 별도 조건을 주면 역적분은 의미가 있습니다.', M(r"H(x)=\int_0^\infty e^{-a\omega}\frac{\sin(\omega x)}\omega\,d\omega,\quad H'(x)=\int_0^\infty e^{-a\omega}\cos(\omega x)\,d\omega=\frac{a}{a^2+x^2}"), M(r"H(0)=0\quad\Longrightarrow\quad H(x)=\int_0^x\frac{a}{a^2+u^2}\,du=\arctan\frac xa,\qquad f(x)=\sqrt{\frac2\pi}\arctan\frac xa"), '이 f는 무한대에서 상수에 접근하므로 절대적분 가능한 함수가 아닙니다. 사인 정변환까지 주장하려면 Abel 수렴 등의 확장 해석을 명시해야 합니다. 위 계산은 우선 수렴하는 사인 역적분의 값입니다.'),
        C('추가 조건에 따라 답이 달라진다', '예를 들어 실수 전체에서 e⁻ᵃ|ω|/(iω)를 주고 원점에 주값을 취하면 √(2/π)arctan(x/a)를 얻습니다. 분모가 ω이면 답은 그 i배입니다. 절댓값·i·변환 종류 중 무엇을 추가하느냐에 따라 문제가 달라지므로, 원문에 없는 기호를 조용히 넣어 하나의 답으로 확정하지 않습니다.', M(r"\frac1{\sqrt{2\pi}}\operatorname{PV}\int_{-\infty}^\infty\frac{e^{-a|\omega|}}{i\omega}e^{i\omega x}\,d\omega=\sqrt{\frac2\pi}\arctan\frac xa\quad(a>0)"))
    ], [
        C('1 · “공식을 넣으면 되겠지” 전에 적분 가능한지 봅니다.', '원문에는 변환 결과가 e⁻ᵃω/ω라고 적혀 있습니다. 앞의 Fourier transform(푸리에 변환)은 음의 주파수부터 양의 주파수까지 모두 사용했습니다. 따라서 역변환도 −∞부터 ∞까지 적분해야 합니다. 양의 주파수만 사용하겠다고 임의로 바꾸면 다른 문제입니다.', M(r"f(x)\stackrel{?}{=}\frac1{\sqrt{2\pi}}\int_{-\infty}^{\infty}\frac{e^{-a\omega}e^{i\omega x}}\omega\,d\omega")),
        C('2 · 원점에서 한 번, 먼 꼬리에서 또 막힙니다.', 'ω가 0에 가까우면 지수함수는 1에 가까워지고, 식은 1/ω처럼 됩니다. 1/ω의 적분은 ln|ω|이므로 원점 한쪽으로만 접근하면 끝없이 커집니다. 양쪽을 특별한 방식으로 동시에 상쇄시키는 principal value(주값)는 보통의 적분과 다른 약속입니다.', '또 a&gt;0이어도 ω가 음수이면 −aω는 양수가 됩니다. ω=−100이면 e¹⁰⁰ᵃ처럼 커지므로 지수 감쇠라고 부를 수 없습니다. 원점 문제만 처리해도 음의 무한대 문제는 남습니다. 그러므로 이 단원의 보통 역변환으로는 원문을 완성할 수 없습니다.'),
        C('3 · 이 문제에서 제출할 수 있는 정확한 결론', '원문에는 a의 범위와 변환 종류·정의역에 대한 추가 조건이 필요합니다. 절대적분 가능한 함수의 보통 Fourier transform(푸리에 변환)이라는 앞선 규약으로는 해당 f가 없습니다. 이것은 계산을 덜 해서 답을 못 얻은 상황이 아니라, 주어진 식이 그 변환의 조건에 들어오지 않는 상황입니다.'),
        C('4 · 별도 예시: 사인 역변환 조건을 주면 왜 풀릴까요?', '이제부터는 원문과 구분한 추가 예시입니다. a&gt;0이고 양의 ω만 사용하며 사인으로 복원한다고 정하면, sin(ωx)가 원점의 문제를 상쇄합니다. 작은 ω에서 sin(ωx)≈ωx이므로 sin(ωx)/ω≈x가 되어 유한합니다.', M(r"H(x)=\int_0^\infty e^{-a\omega}\frac{\sin(\omega x)}\omega\,d\omega")),
        C('5 · x로 미분하면 까다로운 분모 ω가 사라집니다.', M(r"H'(x)=\int_0^\infty e^{-a\omega}\cos(\omega x)\,d\omega=\frac{a}{a^2+x^2}"), 'sin(ωx)를 x로 미분하면 ωcos(ωx)가 나오므로 분모의 ω가 약분됩니다. 오른쪽 적분은 p.14에서 이미 풀었습니다. 이번에는 적분변수가 ω이고 코사인의 상수 역할을 x가 맡았을 뿐입니다.'),
        C('6 · 미분한 것을 되돌리고 시작값을 맞춥니다.', M(r"H(x)-H(0)=\int_0^x\frac{a}{a^2+u^2}\,du=\arctan(x/a),\qquad H(0)=0"), 'arctan은 tangent(탄젠트)의 역함수입니다. tan θ=x/a를 만족하는 −π/2&lt;θ&lt;π/2의 각을 뜻합니다. 사인 역변환 상수 √(2/π)를 마지막에 붙이면 아래 값입니다.', M(r"f(x)=\sqrt{\frac2\pi}\arctan(x/a)"), '이 값은 “양의 주파수의 사인 역적분”이라는 추가 조건에서만 얻었습니다. 무한대에서 0으로 가지 않아 앞 단원의 절대적분 조건과도 다릅니다. 원문의 일반 Fourier transform(푸리에 변환) 답이라고 그대로 적지는 않습니다.')
    ], role='연습문제·조건 검토와 조건부 풀이', audit='원본은 e⁻ᵃω/ω이고 절댓값·i·사인 변환이라는 지정 및 a의 조건은 없습니다. 보통의 전구간 역변환이 성립하지 않는 이유를 설명하고, 별도 조건을 명시한 사인 역적분과 주값 예시를 구분합니다.')
